### ISSUE TITLE
Everytime Crashing When Click On Surevy

### ISSUE THREAD

**Issue by AnkurJagani** [BitBurst-GmbH/bitlabs-android-library#15]
I am getting crash everytime i am clicking on Survey Item. I am using latest 3.1.4 version.

Here is the logcat report

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.appsuite.earn.money.playing.games, PID: 8244
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appsuite.earn.money.playing.games/ai.bitlabs.sdk.views.WebActivity}: java.lang.NullPointerException: null cannot be cast to non-null type android.graphics.drawable.GradientDrawable
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3868)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4010)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:240)
        at android.os.Looper.loop(Looper.java:351)
        at android.app.ActivityThread.main(ActivityThread.java:8381)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
     Caused by: java.lang.NullPointerException: null cannot be cast to non-null type android.graphics.drawable.GradientDrawable
        at ai.bitlabs.sdk.views.WebActivity.bindUI(WebActivity.kt:87)
        at ai.bitlabs.sdk.views.WebActivity.onCreate(WebActivity.kt:49)
        at android.app.Activity.performCreate(Activity.java:8397)
        at android.app.Activity.performCreate(Activity.java:8370)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3841)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4010) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:240) 
        at android.os.Looper.loop(Looper.java:351) 
        at android.app.ActivityThread.main(ActivityThread.java:8381) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013) 
```
Would you please help me? I have spend almost two days in this.

**Comment by AnkurJagani** [comment]
@omaRaad Problem is not because of toolbar not being inflated. it was due to same file name `activity_web.xml` was available in my app module. And whenever bitlab SDK needed content view it was redirecting to my app module and not the actual library's `activity_web.xml`. So simple **solution is I have changed my app module's `activity_web.xml` to `my_activity_web.xml`**. I hope it may help someone who is facing the issue!

**Comment by omaRaad** [comment]
@AnkurJagani Thanks for the update. I have changed all the id names of the view components to unique names that are hard to be duplicated by adding `bl` to them. However, I didn't do that for the `activity_web.xml`. I will do that in the next update.
